from fpdf import FPDF
import os
import json
from .Utils import CONFIG, ROOT_PATH

class BankPDFGenerator(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(20, 40, 100)
        self.cell(0, 15, 'DIGITAL BANK ORGANIZATIONAL STRUCTURE', border=0, align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Confidential - Generated by RAG-Destroyer Industrial AI - Page {self.page_no()}', 0, 0, 'C')

def generate_org_pdf(output_path, org_config):
    pdf = BankPDFGenerator()
    pdf.add_page()
    
    # Section 1
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, '1. Executive Roles & Command Access', border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    pdf.set_font('helvetica', '', 11)
    for role in org_config.get('roles', []):
        access = role['access']
        if isinstance(access, list):
            access = ", ".join(access)
        
        pdf.set_font('helvetica', 'B', 11)
        pdf.write(7, f"{role['role']}: ")
        pdf.set_font('helvetica', '', 11)
        desc = role.get('description', 'High-level management and oversight.')
        pdf.write(7, f"{desc} ")
        pdf.set_font('helvetica', 'I', 10)
        pdf.write(7, f"(Access: {access})\n")
        pdf.ln(5)
    
    pdf.ln(10)

    # 2. The Banking Family Tree (5-Layer Hierarchy)
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, '2. The Banking Family Tree (5-Layer Hierarchy)', border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    for dept in org_config.get('departments', []):
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(20, 40, 100)
        pdf.cell(0, 8, f"Department: {dept['name']}", border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        
        pdf.set_font('helvetica', '', 10)
        h = dept.get('hierarchy', {})
        tree_lines = [
            f"  [L1] {h.get('L1', 'CEO')}",
            f"    |-- [L2] {h.get('L2', 'C-Suite')}",
            f"       |-- [L3] {h.get('L3', 'VP')}",
            f"          |-- [L4] {h.get('L4', 'Manager')}",
            f"             |-- [L5] {h.get('L5', 'Officer')}"
        ]
        for line in tree_lines:
            pdf.cell(0, 6, line, border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    pdf.ln(5)

    # 3. Departmental Subsets
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, '3. Departmental Data Taxonomies', border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    # Table Header
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_fill_color(220, 230, 245)
    
    w_dept = 40
    w_code = 20
    w_types = 130
    
    pdf.cell(w_dept, 10, 'Department', 1, 0, 'C', 1)
    pdf.cell(w_code, 10, 'Code', 1, 0, 'C', 1)
    pdf.cell(w_types, 10, 'Primary Document Types', 1, 1, 'C', 1)
    
    # Table Content
    pdf.set_font('helvetica', '', 9)
    for dept in org_config.get('departments', []):
        types = ", ".join(dept.get('doc_types', []))
        pdf.cell(w_dept, 10, dept['name'], 1)
        pdf.cell(w_code, 10, dept['code'], 1, 0, 'C')
        pdf.cell(w_types, 10, types, 1, 1)

    pdf.ln(10)
    pdf.set_font('helvetica', 'I', 10)
    pdf.multi_cell(190, 7, "Security Notice: All documents within these subsets are protected by the RAG-Destroyer Subset Isolation Layer. Unauthorized access is blocked at the bot kernel level.")

    pdf.output(output_path)
    return output_path

if __name__ == "__main__":
    from .Utils import get_org_config
    config = get_org_config()
    target = os.path.join(ROOT_PATH, "Digital_Bank_Org_Chart.pdf")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    generate_org_pdf(target, config)
    print(f"✅ Beautiful PDF Generated at {target}")
