import os
import re
import json
import frontmatter
import time

from .Utils import CONFIG, document_visible_to_viewer
from .sources import build_knowledge_source

class SearchWorker:
    """A bot that searches for a specific keyword within an authorized subset of the vault."""
    
    def __init__(self, vault_path="knowledge"):
        self.vault_path = vault_path
        self.source = build_knowledge_source(
            CONFIG.get("KNOWLEDGE_SOURCE_BACKEND", "localfs"),
            self.vault_path,
        )
        self._last_cache_fresh_at: float = 0.0
        self._cache_fresh_ttl_sec: int = 120

    def _count_md_under(self, subset: str) -> int:
        """Recursive .md count under vault_path/subset (matches VaultWarden rules)."""
        return sum(1 for _ in self.source.iter_markdown_files(subset))

    def _total_md_in_vault_departments(self) -> int:
        """Count .md under each top-level silo folder (not root files)."""
        return sum(self._count_md_under(name) for name in self.source.list_departments())

    def _cache_is_stale(self, cache_data: dict, allowed_subsets) -> bool:
        """If index on disk has far more docs than _SEARCH_CACHE.json, cache is stale — prefer slow walk."""
        now = time.time()
        if self._last_cache_fresh_at and (now - self._last_cache_fresh_at) < self._cache_fresh_ttl_sec:
            return False
        nd_total = self._total_md_in_vault_departments()
        nc_total = sum(len(v) for v in cache_data.values() if isinstance(v, list))
        if allowed_subsets == "ALL":
            if nd_total == 0:
                self._last_cache_fresh_at = now
                return False
            # Ratio-based rule: fallback only when cache misses a significant portion.
            coverage = (nc_total / nd_total) if nd_total else 1.0
            if nc_total == 0 or coverage < 0.70:
                print(
                    f"[SearchWorker] Cache incomplete for ALL scope "
                    f"(indexed~{nc_total} vs disk~{nd_total}, coverage={coverage:.2f}). Using slow walk."
                )
                return True
            self._last_cache_fresh_at = now
            return False
        subs = allowed_subsets if isinstance(allowed_subsets, list) else [allowed_subsets]
        for subset in subs:
            if not isinstance(subset, str):
                continue
            nd = self._count_md_under(subset)
            nc = len(cache_data.get(subset, []))
            if nd > 0 and nc == 0:
                print(f"[SearchWorker] Cache empty for '{subset}' (disk={nd} files). Using slow walk.")
                return True
            if nd >= 8 and nc < max(2, nd // 4):
                print(f"[SearchWorker] Cache stale for '{subset}' (cache={nc} vs disk={nd}). Using slow walk.")
                return True
            if nd > 15 and nc <= 3:
                print(f"[SearchWorker] Cache out of date for '{subset}' (cache={nc} vs disk={nd}). Using slow walk.")
                return True
        self._last_cache_fresh_at = now
        return False

    def _filter_results_by_audience(
        self,
        results: list,
        viewer_role: str | None,
        viewer_active_department: str | None = None,
    ) -> list:
        if not results:
            return results
        out = []
        for hit in results:
            basename = os.path.basename(hit["path"])
            dept = hit.get("department") or ""
            try:
                post = frontmatter.load(hit["path"])
                if viewer_role is not None and not document_visible_to_viewer(
                    viewer_role,
                    dept,
                    basename,
                    post.get("audience"),
                    viewer_active_department,
                ):
                    continue
                out.append(hit)
            except Exception:
                if viewer_role is not None and not document_visible_to_viewer(
                    viewer_role,
                    dept,
                    basename,
                    None,
                    viewer_active_department,
                ):
                    continue
                out.append(hit)
        return out

    def search(self, keyword, allowed_subsets=None, viewer_role=None, viewer_active_department=None):
        """High-speed search using the JSON cache generated by VaultWarden."""
        if not allowed_subsets:
            return []

        results = []
        keyword = keyword.lower()
        
        cache_path = self.source.cache_path()
        if not os.path.exists(cache_path):
            print("[SearchWorker] Cache not found. Running slow search...")
            return self._filter_results_by_audience(
                self._slow_search(keyword, allowed_subsets),
                viewer_role,
                viewer_active_department,
            )

        with open(cache_path, 'r', encoding='utf-8') as f:
            cache_data = json.load(f)

        if self._cache_is_stale(cache_data, allowed_subsets):
            return self._filter_results_by_audience(
                self._slow_search(keyword, allowed_subsets),
                viewer_role,
                viewer_active_department,
            )

        # Determine actual subsets to search (ALL must union disk folders — cache may omit e.g. General)
        if allowed_subsets == "ALL":
            disk_dirs = self.source.list_departments()
            target_subsets = sorted(set(cache_data.keys()) | set(disk_dirs))
        else:
            target_subsets = list(allowed_subsets)

        for subset in target_subsets:
            if subset not in cache_data:
                results.extend(self._slow_search(keyword, [subset]))
                continue

            for doc in cache_data[subset]:
                relevance = 0
                title = doc["title"].lower()
                tags = str(doc.get("tags", [])).lower()
                summary = doc.get("summary", "").lower()
                
                if keyword in title: relevance += 10
                if keyword in tags: relevance += 5
                if keyword in summary: relevance += 3
                
                if relevance > 0:
                    # Construct full path for Orchestrator to read
                    full_path = os.path.join(self.vault_path, subset, doc["path"])
                    results.append({
                        "path": full_path,
                        "title": doc["title"],
                        "relevance": relevance,
                        "department": subset,
                        "tags": doc["tags"],
                        "summary": doc["summary"],
                        "doc_id": doc.get("doc_id", "N/A"),
                    })
        
        return self._filter_results_by_audience(results, viewer_role, viewer_active_department)

    def _slow_search(self, keyword, allowed_subsets):
        """Fallback: walk markdown vault when _SEARCH_CACHE.json is missing."""
        results = []
        keyword = keyword.lower()
        if not allowed_subsets:
            return results

        if allowed_subsets == "ALL":
            target_subsets = self.source.list_departments()
        else:
            target_subsets = list(allowed_subsets)

        for subset in target_subsets:
            for file_path in self.source.iter_markdown_files(subset):
                file = os.path.basename(file_path)
                try:
                    post = frontmatter.load(file_path)
                except Exception:
                    continue
                title = (post.get("title") or file).lower()
                tags = str(post.get("tags", [])).lower()
                summary = (post.get("summary") or "").lower()
                relevance = 0
                if keyword in title:
                    relevance += 10
                if keyword in tags:
                    relevance += 5
                if keyword in summary:
                    relevance += 3
                if relevance > 0:
                    results.append({
                        "path": file_path,
                        "title": post.get("title", file),
                        "relevance": relevance,
                        "department": subset,
                        "tags": post.get("tags", []),
                        "summary": post.get("summary", ""),
                        "doc_id": post.get("doc_id", "N/A"),
                    })
        return results
